backend:
  name: test-repo
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "src/site/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "title.md" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.njk" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: "post"}
      - { label: "Publish Date", name: "date", widget: "datetime"}

  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "src/site"
    create: true # Change to true to allow editors to create new pages
    slug: ""
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.njk" }
      - { label: "Body", name: "body", widget: "markdown" }